import type { CardModel } from './model/types';

export const demoCards: CardModel[] = [
  {
    kind: 'spell',
    id: 'card-001',
    name: 'Fireball',
    cost: 3,
    attack: 5,
    descr: 'Deal 5 damage to target.',
  },
  {
    kind: 'unit',
    id: 'card-002',
    name: 'Goblin',
    cost: 0,
    descr: 'Weak goblin',
    hp: 50,
    attack: 15,
    effects: ['swarm'],
    unitSpriteSrc: '/assets/card/units/goblin.png',
    artSrc: '/assets/card/art/goblin.png',
  },
  {
    kind: 'unit',
    id: 'card-004',
    name: 'Knight',
    cost: 6,
    descr: 'Knight',
    hp: 150,
    attack: 45,
    effects: ['acceleration'],
    unitSpriteSrc: '/assets/card/units/placeholder.png',
    artSrc: '/assets/card/art/placeholder.png',
  },
  {
    kind: 'unit',
    id: 'card-003',
    name: 'Dragon',
    cost: 9,
    descr: 'Green dragon',
    hp: 350,
    attack: 65,
    effects: ['splashAttack'],
    unitSpriteSrc: '/assets/card/units/placeholder.png',
    artSrc: '/assets/card/art/placeholder.png',
  },
  {
    kind: 'unit',
    id: 'card-005',
    name: 'Wolf',
    cost: 5,
    descr: 'Wolf',
    hp: 90,
    attack: 35,
    effects: ['bite'],
    unitSpriteSrc: '/assets/card/units/placeholder.png',
    artSrc: '/assets/card/art/placeholder.png',
  },
  {
    kind: 'unit',
    id: 'card-006',
    name: 'Orc',
    cost: 7,
    descr: 'Orc',
    hp: 150,
    attack: 55,
    effects: ['stun'],
    unitSpriteSrc: '/assets/card/units/placeholder.png',
    artSrc: '/assets/card/art/placeholder.png',
  },
  {
    kind: 'unit',
    id: 'card-007',
    name: 'Archer',
    cost: 3,
    descr: 'Archer',
    hp: 40,
    attack: 25,
    effects: ['bow'],
    unitSpriteSrc: '/assets/card/units/placeholder.png',
    artSrc: '/assets/card/art/placeholder.png',
  },
];
